title: qiang5062250 / 小强
description: A cat who writes code

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/qiang5062250
  - title: Email
    img: /assets/images/gmail.png
    url: mailto:root@30pu.net

avatar: /assets/images/avatar.png
introduction: >
  Hi! My nickname is qiang5062250.<br/>
  中文昵称是流浪小猫，也可以叫我小猫。<br/>
  Whenever you see this lovely cat, yeah that’s me!

projects:
  title: Open Source Projects
  github:
    - qiang5062250/mobi.css
    - qiang5062250/typescript-tutorial
    - qiang5062250/react-ie8
    - qiang5062250/jekyllcn
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/qiang5062250">github.com/qiang5062250</a>.</p>
    <p>If you love my projects, please <a href="https://github.com/qiang5062250/buy-me-a-coffee">buy me a coffee</a> to support me.</p>

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Microsoft: Software Engineer II"
    - date: 2016-04
    - "Meituan: Senior Front-End Engineer"
    - date: 2015-04
    - "Meituan: Front-End Engineer"
    - date: 2013-06
    - "Meituan: Front-End Engineer Internship"
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: 2013-06
    - "Bachelor of WuHan University: Computer Science and Technology"
    - date: 2009-09

google_analytics: UA-45256157-13

theme: jekyll-theme-cayman